name = '灵明字根简码练习'
version = '无'
config_version = "2026.2.7-1"
help = ['''
<div class="card">
    <style>
        .chars-table {
            width: 60%;
            margin-left: 0;
        }
        .words-table {
            width: 40%;
            margin-left: 0;
        }
        th, td {
            text-align: left;
            vertical-align: middle;
        }
    </style>
    <div class="help-block"><h3>单字规则</h3>
        <p>首根首码 A，首根次码 a，次根首码 B，三根首码 C，末根首码 Z，末根次码 z，字根第三码 x</p>
        <div class="help-items">
            <table class="chars-table">
                <thead>
                <tr>
                    <th>首根是大根</th>
                    <th>首根是小根</th>
                    <th>字根数</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><code>Aax</code></td>
                    <td><code>Aa</code></td>
                    <td>单根字</td>
                </tr>
                <tr>
                    <td><code>AaZz</code></td>
                    <td><code>AZzx</code></td>
                    <td>双根字</td>
                </tr>
                <tr>
                    <td><code>AaBZ</code></td>
                    <td><code>ABZz</code></td>
                    <td>三根字</td>
                </tr>
                <tr>
                    <td><code>AaBZ</code></td>
                    <td><code>ABCZ</code></td>
                    <td>多根字</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="help-block"><h3>词组规则</h3>
        <p>首字首码 A，首字次码 a，二字首码 B，二字次码 b，三字首码 C，末字首码 Z，末字次码 z</p>
        <div class="help-items">
            <table class="words-table">
                <tbody>
                <tr>
                    <td><code>AaBb</code></td>
                    <td>二字词</td>
                </tr>
                <tr>
                    <td><code>ABZz</code></td>
                    <td>三字词</td>
                </tr>
                <tr>
                    <td><code>ABCZ</code></td>
                    <td>多字词</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="help-hint">💡 点击上方分类开始练习</div>
</div>
''']

text = [
    { name = '字频 1500 前 500', content = "的一了是不在他我人这有你来道上个大也说就到着中那地和她出为之要下们时以得会都可子去对能过而然看还自后里天没国好么小年发起想多只生心事家如又无于种手所但已两身前法用头面点开成方将同声当很些与知从行把此现其见经等老被实作最力给意样动笑长向间进神三十回真本主日分什部正者定使眼话问再却情学走己气高才几更明太因外位让便打门次应全新月儿并二口名死第听女相内公理军重王别它白战山文光体先由入少比住机做关像变直处师果何书西通数水至金接带特色边感快世安物提东四张许总叫觉信望平剑性吗风立轻空放难马美指海传加脸强吧连化或民怎常原合目呢工飞场转远完清命度花五该李教杀制吃各任万今及受表条非跟解利元算路啊城代黑反落言德件题候未则百林结满往斯业活火思量必倒即界电步找龙云极士每流且南似修认石系离虽令竟若灵双论请红管夫尔干影谁深近政字半亲青惊形义血车爱坐产确刚早兵队微记展院罗精报怕武北片拉收随据根交越计语始保七击失官绝站钱治员拿乎夜克象陈建星古千达刻功帝期周写九敢取朝送区市求容尽整族复司息冷八决存叶般统众音告程够领类识衣断苏哪术办江服切错观紧奇格派品甚消魔破仙式六留冲房底准楚府务突资基视境帮掌曾黄刀单注台皇伤势级段句运谈" },
    { name = '字频 1500 中 500', content = "怪阳响足终布况弟华阿首备玉持证急社另男酒阵显喜章需低暗待改药宝造久照沉集团图设科娘器铁父易装联权除异晚忙英故史约客号雷圣州线具共君依敌静您引争宗考楼喝念兴支斗调脚群穿包速兄掉商木继组称刘差疑属苦答既乐友河乱攻议顿初愿选仍哥仅规围座续推须忽招停专细病护爷究居害孩跑曰施退姐价鬼置摇举母嘴节威讲射份左丝导雪质隐脑历游土哈船局巴莫查陆技示树热香巨党秦升较广闻守背汉京追宫换副岁块试佛某散态密层露希独角余米费欢压尊济亚顾闪按右封止呼致股福银料严旁参默怀兰怒志礼恐简慢赶遇室齐虚际投承项痛值谢纪肯亦宋祖研宁梦靠恶标防狂波玩印买超网宇阴忍魂跳凡助杨亮卫排震增养营救尚食维胜皮画医模雨假列唐否划状察刺毛弹诸叹案卷险激村睡淡归挥堂呀妈抓鱼环睛逃欲源省顶妖旧藏读春醒缓赵耳烟肉诗负胡草毒素屋虎效贵普枪拍松萧型翻范丹球诉炼寻委农乃秘吸镇姑卡校眉钟责县晓验洞景灭毕渐冰恩危骨练索寒略孙充烈徐善罪域蓝猛担野批率韩伯顺沙店弄峰职获牛采禁临毫味抱降限秋脱创短永丽田抬警户端供兽忘败构著配习占臣免皆盘啦迎探弱卖律姓阶饭坏例控湖演床笔缺辈尼甲适幸夏纳谓殿骑测伙凤玄企借戏妹温扬登朋坚轰富良混罢辰板哭航握版预革托暴付替朱透拳轮织吴移浪" },
    { name = '字频 1500 后 500', content = "庄伸歌喊执厉宣休释雄紫犯摆麻妇徒架监蒙讨园杂丈套谷益艺征词伊避审优赛呆恨洛岛劳舞尘剧盖熟瞧积牙庆咱财洲纯碎硬抗育曲迷氏犹拜桌狗奔凌秀判懂闭遍概智亡纷瞬横凝邪柳仿闲绿爆墙郎御述班乡遗材闹腿摸郑洋吓附补炮侧含劲妙策残厅纸互款评胸误偷符街茶尸烧困挑偏骂唯颗柔抽尖珠馆趣束丁灯拥聚肩输盛叔狠鲜货庭择搞迹雅敬鲁编奥圆均稍检康荒贝烦挂凶浮窗录篇吉凭幽裂躲岂幕扑牌欧燕尤贼纵稳序梅泪沈席固博冒塔虑腰折炸夺伦额软雾袋介距缘婚诺私午油逐妻哼彩灰扫协遭森泽荣洗票抢飘销侯厚塞宽抵碰番载惨跃触曹损舍迅减核斩伏呵滚杯巧逼弃咬竹孤末嘛乌孔谋撞袭圈菜劫挺厂延戴皱疯羽盯箭仇杜杰镜授彻狼壁毁婆操赤鼓臂川梁幻踏隔库颜乘典吹页讯迫舰奉盟凉脉荡洪吐蛇腾疾忠萨尾累爸炎惜童训悲辛努锋丢陷愈莱岸陪猜涌嗯阻剩访挡迟针诚鸟勒魏侍唱哦芒鸣瞪爵废启仰税绕颇括旋阁堆督拔献翼颤娇赞胆豪潜络牧虫锁旅宜融净央苍晶健耀尺裴勇墨缩奴途仁穷眸召鸡赏仪港薄粉映隆予吼彼忧躺旦伟拖爬睁桥恢丰愣吾悟筑贴奶奈爹振刑倾壮俩染唇俄暂霸枫漫倍吞朗粗奋递孟蛋扶陵坦侠池忆怨垂餐插浓遂惑昨冬汤莲辞俱掩怔怜殊泰珍抖摩扎旗鼻舒姆晋驾码仔浩枚渡申伴僧祭恰瓶晨惯枝尝娜俗悄袍辆唤矣辉奏狐" },
    { name = '字频 3000 前 500', content = "季乔晃幅浑匹潮零昏羊奖姜劝岩悉径侵亿聊磨疗曼耐佳艾享愤沿课拼汗偶糊估骗铺驻抹抚绍惧扭吕渊郡嘉汇拒丧瓦狱庙瑞析贤冥滑粮俊欣泥袖扩湾盗扯铜芳赫焰甘兼迁戒伍疼哲遥购傻寿敏饮朵贫貌郭闷佩返竞廷译慌麦恭卿泉燃础钢猫怖截琴耶培喷堡援箱帐泛慕胖井敲促忌庞掠堪擦遣撤熊岳绪帅醉捕董酸悬柄铮埃猎肃焦吟昊币椅踪斜嘿牵搭嫁柱吻缠亏袁播宿惹跪寺滴赐埋冠玛弯穴灾钻坛祝秒罚描违傅搜腹宙烂订患夹慧液刊寂巡傲罩喂耗纹摄牢蛮植幼锦卢仗陛繁弗届鹰欺屈劈邦浅赖舟卧雕撒丑键暮晴刹漠贸涉菲仆恋签痕允凯碧贺漂宾霍勾姬措愁悠衡役碗逆崇桑匆赌慈寸寄笼扇姿抛挤赋迪拦汽赢弥恒询售覆逸赴讶豫跨跌恼艘亭盾贯撑详缝扰乾扣汪肚啸韦洁躯频蒂瘦黎崩艳猪溜趁贾孝锐捉挣祸拨悦聪津砸炉桃羞阅籍屏饰诏煞仲莉稀刃哀翠喘鞋豆薛裁霞割棋障郁矛拾扔疏闯啥蒋姊昌契妮谦衫刷驱冯鸿脏祥儒搬披催帽勤迈悔砍污慰荷骇霜润惠柯眨喃晕嫌宰耸辑欠厌卒魄痴辩宅旨舌呈惟脆矿娃墓茫踢拟崔湿咳暖弓凑鞭丫鼎昭胁婴屁储驶挖懒宏焉册尉崖署姨璃叛饿溪鼠串唉爪陶诡屠轩饶穆卓租邓夕铃励遮膀砰肥齿梯龄捏勃债涂碍吏鹏摔婉丛伪邀媒乙撕哩捧症窝仓涨贡贪葬瑶妃盒畏斥娶臭誉伐阔趟糟歇乏葛旺慎吊杖粒毅巫诱削帕辱宴添掏" },
    { name = '字频 3000 中 500', content = "沟昆谨盈绩坑咒腐枯昔宪瓜奸玲藤彭坡辅链疲眯叙滋愚勉凄锅颈趋洒溃械妄押甜乖肤挨咽蝶僵赚虹肠偿纠柜邻朕账愧摘姚斤昂夸矮坠岗肖媚艰裹驰爽寨瑟逢档靖丘稿禅镖苗甫瞒厨妥脖肌漏骤筹扮吵踩宠鉴膝泄琳抑雀柴莎囊循鹿翁衰饱灌翅甩鹤哎湘狄俯绳遵愕辨泡裤卜陌揭戈赠涛捷羡漆逊胞宛窜岭遁桂综韵摊麽狮戚瞎夷酷沾辽咕咐盐谱殷龟沐剂牲吨裙蹲誓棍盼薇矩骄纤厮杆瞥蕴恍舱寇疆後廉玻逝拆拢汝赔蔡艇耍巾卑缕肿肆棒嘻拂纱糖歪绣逻啪盆陡诊廊贞倘淮柏慨凛壳吩兹拐哑芝妨侦叠揉猿擅歉嫂陀诞芬嚷钉捌腕辟胎蠢壶株碑栏噬隶叉巅眠渔掀巷蜂潘诛嘶抄坊擒豹携畅荆斑禄翎叮坤亩绵渴挽辣诀咧棺妾筋肝忖竖填噗竭敛弦佐拱骸匪剥践喉堵沌呜邮翰岚氛窃躬猴瞳耻哇帘棵沃攀拓哉嘲萍莹屑绘翔腊勋冤淋寡剪焚粹烛搂榜轨琼於魅贱腔雁桩禀乞颊秩霄浴铭揞兆勿巢览尿琪殖哗钩蓄蔽倚锤兔峡荐蓬蜀弘蜜麟侄衍丞婢罕舅丐淫颠愉衙挪斧轿尹祈钦厢劣塌撼晰乳脾谅阎搏茂丸绑畜搁履敦泣雇朽磁冻朴兮塑庸笨泊彦悍坟恕蓉栽裕嗡棉券址魁捡憾郊兜璇扁澳珊凰铸桐纽惶烁咦棠驳绽诧烤帆耕沧纲煤函贷哄斋牺蛛吁讽溢灿咸摧黛惩胃聂匠嘱俏隙伞撇筒滞刮莽栋枕秃尴泼浸嗤逗狭熙辖桶嫩犬鸦寓倏掷顽哟芦襄桓骆瞄饥俺盏尬囚趴虞嗓溅谭孽朔" },
    { name = '字频 3000 后 500', content = "帖叱胀滩裸淑骚酬徽鳞嫣躁缚哨仑滔畔庚拘丙邵窍茅谎涯姻蔓锡兀菩佣钓倩胶蚁潭肺咚喻乍孕咖樱妆耽砖缴噢逛钧煮瞅晌叩逍衷撰黯猩饼鄙霆蛟倦膊熬窥婷枢腥蹄稽毙肢膜澜硕诈颅昧苑雍鸭蒸堤罐藉堕捂浙疫聘塘鞘唬掘裳嗣萝渗菌媳芙呐铠胳煌俘盲衔戮禽寝玫菱澄颖怯菊浆灼呃矢挟厄扛涵衬鲍糕钥谊脂棚梭驴屡顷渠薪捐逾逮鹅痒卦捞蒲喔淹谕脊槐蓦搅卸粘炽旬窄怡瓷浦佑啡梳杭嘟窟淌屯耿霉挠虏陨杏沸篷蚀歹阙睹苟恳垒涩嗷弩陕蝉框绞妒茨咋喀巳栗槽匙啧叟翘磕弊匿庶汹卵诵汁咯旭虐枉憋癌佬炭慑敝瑰厦篮蛊傀僚轴芸哮晒泳滥颂贩烫琉娅煜笛粟舆涡狞俞弧腻辜眩嚣嚎嘘罡渺嗅旱炒琢穹睿冈惕驼掐祀寅嵌馨戳昼膛戟榻歧谏赦蕾喧祷尧暇葡娟栖稚歼彪蹙萌讼捆邑峻挫涅揽拎蹦沫迭眷寞亨伺氧奢觑咨碌墟绸垫吱淳绷咔抿捣咆傍娱揪嗖兑阮妓馀冀叨拧唔芽藩庇楞狡钗梨苹砂詹隋璨澡敞嚼雯惮绮犀邱锻巍侣仕螺葱跋庐芷簿蔑斐咏瑜嘎嘀儡咪戎亥莺坎旷颔绢瀚贬驭戊闺凳啼谜垃琅豁簇鸾揖鲸妍滨斌樊拙幢萱绅宵彷淘邸阐狸拽葫窦婿熄谐圾箫懵舔饲倡祠郎卯陋郝颓婶褚讥厘溶揣姥绰僻辕蜡栈壬梢剖嫉梵癸粥搓钞嗦梧鏊玑胧絮墅焕匈擎忿蚕敷侮嗽宦拚厥朦诣笃沦晦盔狙舵倪醋琐肘浊诅皓撩惭潇匣喇泻揍敕驿蹈凸酿沼毋嗔踱蟒谬叁靴敖镶" },
    { name = '冰灯', content = "冰灯是流行于中国北方的一种古老的民间艺术形式。因为独特的地域优势，黑龙江可以说是制作冰灯最早的地方。传说在很早以前，每到冬季的夜晚，在松嫩平原上，人们总会看到三五成群的农夫和渔民在悠然自得地喂马和捕鱼，他们所使用的照明工具就是用冰做成的灯笼。这便是最早的冰灯。当时制作冰灯的工艺也很简单，把水放进木桶里冻成冰坨，凿出空心，放个油灯在里面，用以照明，冰罩挡住了凛冽的寒风，黑夜里便有了不灭的灯盏，冰灯成了人们生活中不可缺少的帮手。后来，每逢新春佳节和上元之夜，人们又把它加以装饰，而成为供人观赏的独特的艺术表现形式。清代《黑龙江外纪》里对此有过详细的记载：“上元，城中张灯五夜，村落妇女来观剧者，车声彻夜不绝。有镂五六尺冰为寿星灯者，中燃双炬，望之如水晶人。”其实，冰灯在南方一些地方也相继出现过。乾隆、嘉庆年间，四川诗人张问陶曾写过一首专门描写冰灯的诗，题名就叫《冰灯》，诗云：“黑夜有炎凉，冰灯吐焰长。照来消热念，凿处漏寒光。影湿星沉水，神清月里霜。三冬足文史，底用探萤囊。”南京诗人金德荣在被谪戍新疆巴里坤时，在其古风长诗《巴里坤冰灯歌》中也咏叹道：“雪山高与天山接，上有万古不化雪。朔风一夜结作冰，裁雪妙手搏为冰。以矾入冰冰不化，以烛照冰光四射。五里之内尽通明，半月能教天不夜。元夕月轮照碧空，大千人入水晶宫。”哈尔滨是中国冰雪艺术的摇篮，哈尔滨冰灯驰名中外，饮誉华夏。哈尔滨大规模有组织地制作和展出冰灯始于1963年，人们利用盆、桶等简单模具自然冷冻了千余盏冰灯和数十个冰花，于元宵佳节在兆麟公园展出，轰动全城，形成了万人空巷看冰灯的盛大场面。至今许多老哈尔滨人回想起来仍然记忆犹新，感慨万千。这也是我国第一个有组织、有领导的冰灯游园会。当时就有人即兴作词，来形容这“万人空巷，盛极一时”的今古奇观：“灯节，灯节，玉树冰灯明月。人山人海兴浓，园北园南烛红。红烛，红烛，普照万民同乐。”冰灯是黑土地的特产，是黑龙江人的骄傲。从盆制冰景到一年一度大规模的冰灯游园会，哈尔滨冰灯艺术日趋成熟，它的影响和辐射早已使其驰名世界，风靡海内外。1985年，勤劳智慧的冰城人民进一步挖掘冰雪热能，开发冰雪资源，以蜚声中外的冰灯游园会为中心，推出了以冰雪艺术、冰雪体育、冰雪文化、冰雪旅游、冰雪经贸为内容的哈尔滨冰雪节，把让人畏惧的冰雪变成了宝贵的自然资源，给冰城之冬增添了盎然的春意。以后每年的1月5日，便成为哈尔滨人民特有的地方性传统节日，北方人改变了足不出户的“猫冬”习惯，开始参加各种冰雪活动，哈尔滨之冬不再寂寞，哈尔滨的冬天热了起来。"}
]

[[fonts]]
name = 'Yuniversus'
file = 'Yuniversus.ttf'
type = 'ttf'
base64 = ''

[[key_bindings]]
key = 'alt+r'
command = 'content_reload'

[[key_bindings]]
key = 'alt+n'
command = 'content_reload'

[[items_meta]]
category = ['roots']
prefix = ['b', 'c', 'd', 'f', 'g']
suffix = []
min_length = 1
max_length = 3
append_suffix = ''

[[items_meta]]
category = ['roots']
prefix = ['h', 'j', 'k', 'l', 'm']
suffix = []
min_length = 2
max_length = 3
append_suffix = ''

[[items_meta]]
category = ['roots']
prefix = ['n', 'p', 'q', 'r', 's']
suffix = []
min_length = 2
max_length = 3
append_suffix = ''

[[items_meta]]
category = ['roots']
prefix = ['t', 'v', 'w', 'x', 'y']
suffix = []
min_length = 2
max_length = 3
append_suffix = ''

[[items_meta]]
category = ['quick_chars', 'pop_chars']
prefix = []
suffix = ['a', 'e', 'u', 'i', 'o']
min_length = 1
max_length = 2
append_suffix = ''

[[items_meta]]
category = ['quick_chars', 'pop_chars']
prefix = []
suffix = ['a', 'e', 'u', 'i', 'o']
min_length = 3
max_length = 3
append_suffix = ''

[[items_meta]]
category = ['quick_words', 'pop_words']
prefix = []
suffix = ['a', 'e', 'u', 'i', 'o']
min_length = 1
max_length = 3
append_suffix = ''

[[items_meta]]
category = ['quick_chars', 'pop_chars']
prefix = []
suffix = ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y']
min_length = 1
max_length = 2
append_suffix = ' '

[[items_meta]]
category = ['quick_words', 'pop_words']
prefix = []
suffix = ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y']
min_length = 1
max_length = 3
append_suffix = ' '

[[tabs]]
label = '快速入门'
type = 'help'
group = '教程'
index = [0]

[[tabs]]
label = 'BCDFG 键字根'
type = 'item'
group = '字根练习'
index = [0]

[[tabs]]
label = 'HJKLM 键字根'
type = 'item'
group = '字根练习'
index = [1]

[[tabs]]
label = 'NPQRS 键字根'
type = 'item'
group = '字根练习'
index = [2]

[[tabs]]
label = 'TVWXY 键字根'
type = 'item'
group = '字根练习'
index = [3]

[[tabs]]
label = '所有字根'
type = 'item'
group = '字根练习'
index = [0, 1, 2, 3]

[[tabs]]
label = '两键上屏字'
type = 'item'
group = '自动上屏练习'
index = [4]

[[tabs]]
label = '三键上屏字'
type = 'item'
group = '自动上屏练习'
index = [5]

[[tabs]]
label = '所有上屏字'
type = 'item'
group = '自动上屏练习'
index = [4, 5]

[[tabs]]
label = '所有上屏词'
type = 'item'
group = '自动上屏练习'
index = [6]

[[tabs]]
label = '所有上屏简'
type = 'item'
group = '自动上屏练习'
index = [4, 5, 6]

[[tabs]]
label = '所有空格字'
type = 'item'
group = '空格上屏练习'
index = [7]

[[tabs]]
label = '所有空格词'
type = 'item'
group = '空格上屏练习'
index = [8]

[[tabs]]
label = '所有空格简'
type = 'item'
group = '空格上屏练习'
index = [7, 8]
