name = 'æ—¥æœˆå­—æ ¹ç®€ç ç»ƒä¹ '
version = 'æ— '
config_version = "2026.2.1-2"
help = ['''
<div class="card">
    <style>
        .chars-table {
            width: 60%;
            margin-left: 0;
        }

        .words-table {
            width: 40%;
            margin-left: 0;
        }

        th, td {
            text-align: left;
            vertical-align: middle;
        }
    </style>
    <div class="help-block"><h3>å•å­—è§„åˆ™</h3>
        <p>é¦–æ ¹é¦–ç  Aï¼Œé¦–æ ¹æ¬¡ç  aï¼Œæ¬¡æ ¹é¦–ç  Bï¼Œä¸‰æ ¹é¦–ç  Cï¼Œæœ«æ ¹é¦–ç  Zï¼Œæœ«æ ¹æ¬¡ç  zï¼Œå­—æ ¹ç¬¬ä¸‰ç  x</p>
        <div class="help-items">
            <table class="chars-table">
                <thead>
                <tr>
                    <th>é¦–æ ¹æœ‰å£°ç </th>
                    <th>é¦–æ ¹æ— å£°ç </th>
                    <th>å­—æ ¹æ•°</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><code>Aax</code></td>
                    <td><code>Aa</code></td>
                    <td>å•æ ¹å­—</td>
                </tr>
                <tr>
                    <td><code>AaZzx</code></td>
                    <td><code>AZzx</code></td>
                    <td>åŒæ ¹å­—</td>
                </tr>
                <tr>
                    <td><code>AaBZz</code></td>
                    <td><code>ABZzx</code></td>
                    <td>ä¸‰æ ¹å­—</td>
                </tr>
                <tr>
                    <td><code>AaBCZ</code></td>
                    <td><code>ABCZz</code></td>
                    <td>å¤šæ ¹å­—</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="help-block"><h3>è¯ç»„è§„åˆ™</h3>
        <p>é¦–å­—é¦–ç  Aï¼Œé¦–å­—æ¬¡ç  aï¼ŒäºŒå­—é¦–ç  Bï¼ŒäºŒå­—æ¬¡ç  bï¼Œä¸‰å­—é¦–ç  Cï¼Œæœ«å­—é¦–ç  Zï¼Œæœ«å­—æ¬¡ç  z</p>
        <div class="help-items">
            <table class="words-table">
                <tbody>
                <tr>
                    <td><code>AaBb</code></td>
                    <td>äºŒå­—è¯</td>
                </tr>
                <tr>
                    <td><code>ABZz</code></td>
                    <td>ä¸‰å­—è¯</td>
                </tr>
                <tr>
                    <td><code>ABCZ</code></td>
                    <td>å¤šå­—è¯</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="help-hint">ğŸ’¡ ç‚¹å‡»ä¸Šæ–¹åˆ†ç±»å¼€å§‹ç»ƒä¹ </div>
</div>
''']

[[fonts]]
name = 'Yuniversus'
file = 'Yuniversus.ttf'
type = 'ttf'
base64 = ''

[[key_bindings]]
key = 'alt+r'
command = 'tab_reload'

[[items_meta]]
category = ['roots']
prefix = ['b', 'c', 'd', 'f', 'g']
suffix = []
min_length = 1
max_length = 3
append_suffix = ''

[[items_meta]]
category = ['roots']
prefix = ['h', 'j', 'k', 'l', 'm']
suffix = []
min_length = 2
max_length = 3
append_suffix = ''

[[items_meta]]
category = ['roots']
prefix = ['n', 'p', 'q', 'r', 's']
suffix = []
min_length = 2
max_length = 3
append_suffix = ''

[[items_meta]]
category = ['roots']
prefix = ['t', 'v', 'w', 'x', 'y']
suffix = []
min_length = 2
max_length = 3
append_suffix = ''

[[items_meta]]
category = ['quick_chars', 'pop_chars']
prefix = []
suffix = ['a', 'e', 'u', 'i', 'o']
min_length = 1
max_length = 2
append_suffix = ''

[[items_meta]]
category = ['quick_chars', 'pop_chars']
prefix = []
suffix = ['a', 'e', 'u', 'i', 'o']
min_length = 3
max_length = 3
append_suffix = ''

[[items_meta]]
category = ['quick_words', 'pop_words']
prefix = []
suffix = ['a', 'e', 'u', 'i', 'o']
min_length = 1
max_length = 3
append_suffix = ''

[[items_meta]]
category = ['quick_chars', 'pop_chars']
prefix = []
suffix = ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y']
min_length = 1
max_length = 2
append_suffix = ' '

[[items_meta]]
category = ['quick_words', 'pop_words']
prefix = []
suffix = ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y']
min_length = 1
max_length = 3
append_suffix = ' '

[[tabs]]
label = 'å¿«é€Ÿå…¥é—¨'
type = 'help'
group = 'å…¥é—¨'
index = [0]

[[tabs]]
label = 'BCDFG é”®å­—æ ¹'
type = 'item'
group = 'é”®ä½ç»ƒä¹ '
index = [0]

[[tabs]]
label = 'HJKLM é”®å­—æ ¹'
type = 'item'
group = 'é”®ä½ç»ƒä¹ '
index = [1]

[[tabs]]
label = 'NPQRS é”®å­—æ ¹'
type = 'item'
group = 'é”®ä½ç»ƒä¹ '
index = [2]

[[tabs]]
label = 'TVWXY é”®å­—æ ¹'
type = 'item'
group = 'é”®ä½ç»ƒä¹ '
index = [3]

[[tabs]]
label = 'æ‰€æœ‰å­—æ ¹'
type = 'item'
group = 'é”®ä½ç»ƒä¹ '
index = [0, 1, 2, 3]

[[tabs]]
label = 'ä¸¤é”®ä¸Šå±å­—'
type = 'item'
group = 'ä¸Šå±ç»ƒä¹ '
index = [4]

[[tabs]]
label = 'ä¸‰é”®ä¸Šå±å­—'
type = 'item'
group = 'ä¸Šå±ç»ƒä¹ '
index = [5]

[[tabs]]
label = 'æ‰€æœ‰ä¸Šå±å­—'
type = 'item'
group = 'ä¸Šå±ç»ƒä¹ '
index = [4, 5]

[[tabs]]
label = 'æ‰€æœ‰ä¸Šå±è¯'
type = 'item'
group = 'ä¸Šå±ç»ƒä¹ '
index = [6]

[[tabs]]
label = 'æ‰€æœ‰ä¸Šå±ç®€'
type = 'item'
group = 'ä¸Šå±ç»ƒä¹ '
index = [4, 5, 6]

[[tabs]]
label = 'æ‰€æœ‰ç©ºæ ¼å­—'
type = 'item'
group = 'ç©ºæ ¼ç»ƒä¹ '
index = [7]

[[tabs]]
label = 'æ‰€æœ‰ç©ºæ ¼è¯'
type = 'item'
group = 'ç©ºæ ¼ç»ƒä¹ '
index = [8]

[[tabs]]
label = 'æ‰€æœ‰ç©ºæ ¼ç®€'
type = 'item'
group = 'ç©ºæ ¼ç»ƒä¹ '
index = [7, 8]
